name 'net_roles'
maintainer 'Arista Networks EOS+ Consultig Services'
maintainer_email 'jere@arista.com'
source_url 'https://github.com/jerearista/chef-net_roles'
issues_url 'https://github.com/jerearista/chef-net_roles/issues'
license 'all_rights'
description 'net_roles demonstrates usage of the Arista EOS cookbook for Chef'
long_description 'net_roles demonstrates usage of the Arista EOS cookbook for Chef through sample recipes, etcmplates, etc.'
version '0.1.0'
depends 'eos'
